### ISSUE TITLE
怎么安装部署

### ISSUE THREAD

**Issue by jet2007** [cocofree/azkaban_assistant#3]
按照你写的部署方案，没能部署成功！

azkaban-web  使用官方的2.5版本
azkaban-executor  使用官方的2.5版本

schedule 使用你的schedule目录；

部署后，没在页面看到“任务调度”项

**Comment by cocofree** [comment]
需要使用代码里提供的azkaban工程去启动，对基于2.5版本的代码改动过，比如添加页面链接、功能扩展

**Comment by jet2007** [comment]
需要把你的web和executor的代码，覆盖到官方的对应文件夹里面？

**Comment by cocofree** [comment]
直接用这两个工程目录就可以，或者把工程下面的jar包覆盖到官方工程下面。

**Comment by jet2007** [comment]
可以直接使用你的工程，可以完全不用官方的了？

**Comment by cocofree** [comment]
刚看了下，我的azkaban工程文件没上传完整，等我晚上回去时更新下，大概二十一点左右

**Comment by jet2007** [comment]
麻烦了

**Comment by cocofree** [comment]
文件更新完成，可以再试试了

**Comment by xutangly** [comment]
好像还是不行，点击“任务配置”会跳转到http://bdata01:8445/job_list

**Comment by cocofree** [comment]
上传成内部版本的JAR包了- -!!!已更正。。
