### ISSUE TITLE
点击'任务配置'失败，也无日志产生，是什么原因

### ISSUE THREAD

**Issue by 540444923** [cocofree/azkaban_assistant#7]
![image](https://cloud.githubusercontent.com/assets/5510617/26752170/926445a2-487c-11e7-8365-d67be72ba37e.png)

![image](https://cloud.githubusercontent.com/assets/5510617/26752194/dbd2f116-487c-11e7-8a29-fa8e68b19561.png)
![Uploading image.png…]()

**Comment by cocofree** [comment]
看下schedule工程是否启动成功，日志里是否有报错

**Comment by 540444923** [comment]
是我配置有问题，没有改动schedule下conf的配置。现在已经运行正常。但是数据库版本过低（5.0.95），修改了表结构中的 多个CURRENT_TIMESTAMP并存的问题，现在已正常启动。

**Comment by cocofree** [comment]
好的，我也调整下这个问题




发自网易邮箱 iPhone 版
在2017年06月06日 12:16，LuoS 写道：

是我配置有问题，没有改动schedule下conf的配置。现在已经运行正常。但是数据库版本过低（5.0.95），修改了表结构中的 多个CURRENT_TIMESTAMP并存的问题，现在已正常启动。
